"""add voice_note_path to tasks

Revision ID: 5377ef585df6
Revises: fa7517eaf875
Create Date: 2026-08-24 17:12:50.409875

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5377ef585df6"
down_revision: str | None = "fa7517eaf875"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("voice_note_path", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "voice_note_path")
    # ### end Alembic commands ###
